include:
- fission.py
kind: ArchiveUploadSpec
name: fission-py-BPfw

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: acc-data-get-fn-fca7d414-49ad-442f-8645-1b78f9e1c604
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://fission-py-BPfw
  environment:
    name: acc-data-get-env
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2023-01-06T15:38:44Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: acc-data-get-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      SpecializationTimeout: 120
    StrategyType: execution
  concurrency: 500
  environment:
    name: acc-data-get-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: acc-data-get-fn-fca7d414-49ad-442f-8645-1b78f9e1c604
      namespace: default
  requestsPerPod: 10000
  resources:
    requests:
      cpu: 128m
      memory: 128Mi
    limits:
      cpu: 256m
      memory: 256Mi
