apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-user-data-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-user-data-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /onboarding/get_user_data
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /onboarding/get_user_data
